Document: statrec
Title: Debian statrec Manual
Author: <insert document author here>
Abstract: This manual describes what statrec is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/statrec/statrec.sgml.gz

Format: postscript
Files: /usr/share/doc/statrec/statrec.ps.gz

Format: text
Files: /usr/share/doc/statrec/statrec.text.gz

Format: HTML
Index: /usr/share/doc/statrec/html/index.html
Files: /usr/share/doc/statrec/html/*.html
